### ISSUE TITLE
Please build image for 1.50.0-nightly (3d6705aa5 2020-12-07)

### ISSUE THREAD

**Issue by contradictioned** [emk/rust-musl-builder#108]
**Rust release:** nightly-2020-12-07

**OpenSSL:** 1.1

Thank you :)

**Comment by contradictioned** [comment]
Slightly off-topic: I used the "Build request" issue template because I wanted to request a build. Is this as you intended it? The "rebuilt" in the about field and the bug-label make me second-guess this. If you thought of this template for requesting rebuilding already published images, I'd suggest renaming it to "Request rebuild".

**Comment by emk** [comment]
You made the request completely correctly! Unfortunately, I was trying to ship a huge project over the holidays and I didn't even see your request in my GitHub notifications. I'll have updated builds out today or tomorrow, with some other changes I've been waiting to release.

**Comment by emk** [comment]
I've now released `nightly-2021-01-01`, which is the [latest build to have RLS and the other major components](https://rust-lang.github.io/rustup-components-history/), as well as 1.49.0.
`

**Comment by emk** [comment]
Thank you for requesting a build! And my apologies for the slow holiday response.
