### ISSUE TITLE
upx support

### ISSUE THREAD

**Issue by GopherJ** [emk/rust-musl-builder#109]
**How could this project be improved?**

musl can generate big binary but makes the program more portable, upx can minimize a binary, is it possible to have it inside the container?

**If you're interested in implementing this feature yourself, how could I help you?**

A workaround will look like

```dockerfile
# Install upx
RUN wget https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz \
    && tar -xJf upx-3.94-amd64_linux.tar.xz \
    && chmod u+x upx-3.94-amd64_linux/upx \
    && sudo mv upx-3.94-amd64_linux/upx /usr/local/bin
```

**Comment by GopherJ** [comment]
Also the size of upx is quite small, like 360K on my pc.

**Comment by emk** [comment]
Apparently UPX has [licensing issues that make it difficult for us to redistribute](https://github.com/jaegertracing/jaeger/issues/1089) and it [breaks page sharing](https://github.com/kubernetes/kubernetes/pull/28265#issuecomment-230124309) resulting in more RAM usage in many common scenarioes. Instead, I would recommend zipping your executables when you distribute them but storing them uncompressed on disk.

But if you want to use `upx`, you should be able to install it normally as part of the Dockerfile that you use to compile your Rust code. Thank you for the suggestion and good luck!
