### ISSUE TITLE
Update to Rust stable 1.51

### ISSUE THREAD

**Issue by apiraino** [emk/rust-musl-builder#121]
**Rust release:** (stable 1.51.0)

I have self rebuilt the image by checking out this repo and run `docker build  . --tag my-musl-builder:1.51.0` basically for one interesting feature I'm using: the new [improved dependency resolver](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver).

When there's a chance, you might want to also update the image on hub.docker.com for others to take advantage.

Thank you for working on this project!

**Comment by apiraino** [comment]
(it's not a bug :smile: )

**Comment by emk** [comment]
We now have up-to-date nightly builds using GitHub CI! Thank you to everyone for the encouragement.
