### ISSUE TITLE
Update to Rust stable 1.53.0

### ISSUE THREAD

**Issue by JMLX42** [emk/rust-musl-builder#123]
**Rust release:** 1.53.0

https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html

**Comment by georglauterbach** [comment]
@emk any chance this could happen in the near future?

**Comment by JMLX42** [comment]
The following command line can be used to build the 1.53 image:

```bash
$ docker build \
    --build-arg TOOLCHAIN="1.53.0" \
    --build-arg OPENSSL_VERSION="1.1.1i" \
    -t "rust-musl:1.53.0" \
    .
```

**Comment by vbrandl** [comment]
I just created https://github.com/emk/rust-musl-builder/pull/126 to switch from the Docker Hub CI to GitHub Actions, since the shutdown of the Docker Hub free tier is the reason, why there are no new versions of the image.

Maybe anyone already built and published Docker images using GitHub Actions can have a look if this is OK or could be improved.

**Comment by gibfahn** [comment]
Just a note that I found specifying a TOOLCHAIN version (as opposed to just `stable` breaks things when your `rust-toolchain` just says `stable` (as rust will start trying to download `x86_64-unknown-linux-gnu` and fail as it's not running as root etc.

Rebuild for [latest openssl 1.1.1](https://www.openssl.org/source/) (and which works to build Rust 1.55.0 as of today):

```shell
docker build --build-arg OPENSSL_VERSION=1.1.1l -t rust-musl-builder .
```

**Comment by dessalines** [comment]
This one worked for me: https://github.com/clux/muslrust

**Comment by emk** [comment]
This is blocked on: https://github.com/emk/rust-musl-builder/pull/126. Please see the discussion there.

**Comment by emk** [comment]
We now have up-to-date nightly builds using GitHub CI! Thank you to everyone for the encouragement.
