### ISSUE TITLE
an unknown tool name found in scoped lint: rustdoc

### ISSUE THREAD

**Issue by Oliboy50** [emk/rust-musl-builder#125]
**What did you try to do?**

I tried to run `docker run --rm -it [-v ...] ekidd/rust-musl-builder cargo build --release` on a project which depends on [the official AWS SDK for Rust](https://github.com/awslabs/aws-sdk-rust)

**What happened?**

```
Compiling smithy-client v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.10-alpha#abe0ae57)
error[E0710]: an unknown tool name found in scoped lint: `rustdoc::all`
 --> /home/rust/.cargo/git/checkouts/aws-sdk-rust-be00ef1d3f696844/abe0ae5/sdk/smithy-client/src/lib.rs:9:5
  |
9 |     rustdoc::all,
  |     ^^^^^^^
error[E0710]: an unknown tool name found in scoped lint: `rustdoc::private_doc_tests`
  --> /home/rust/.cargo/git/checkouts/aws-sdk-rust-be00ef1d3f696844/abe0ae5/sdk/smithy-client/src/lib.rs:18:9
   |
18 | #[allow(rustdoc::private_doc_tests)]
   |         ^^^^^^^
error: aborting due to 2 previous errors
For more information about this error, try `rustc --explain E0710`.
error: could not compile `smithy-client`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

**What did you hope to happen?**

Compiling works without error... I think it misses some "rustdoc" dependencies for that (maybe using some `rustup component add ...` commands or something), but I can't tell which one... 

All I can say is that I am able to run `cargo check` on MacOS with a default rustup installation 🤷 

**Additional information**

I created an issue on AWS side too: https://github.com/awslabs/aws-sdk-rust/issues/156 ... because I can't tell who's wrong in this story

**Comment by Oliboy50** [comment]
Is it missing some `rustdoc` component here: https://github.com/emk/rust-musl-builder/blob/master/Dockerfile#L141-L149

**Comment by Oliboy50** [comment]
it seems that you just need to update the Rust version to `1.52.0` to fix my issue

because these `rustdoc::` stuff was added [in 1.52.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#rustdoc-1)

**Comment by Oliboy50** [comment]
so #122 or #123 should fix this 🤞

**Comment by emk** [comment]
This is blocked on #126.

**Comment by emk** [comment]
We now have up-to-date nightly builds using GitHub CI! Thank you to everyone for the encouragement.
