### ISSUE TITLE
Build request: nightly-2021-06-01

### ISSUE THREAD

**Issue by Ploppz** [emk/rust-musl-builder#128]
**Rust release:** nightly-2021-06-01

Thanks!

**Comment by fabioberger** [comment]
I was about to submit a request as well, but is there anyway we can do this ourselves so future users aren't bottlenecked here?

**Comment by dessalines** [comment]
@emk we need some new builds, especially for `1.56.0` badly.

**Comment by dessalines** [comment]
Finally found a good new musl image to use: https://github.com/clux/muslrust

I suggest ppl switch to it because this one seems abandoned.

**Comment by emk** [comment]
This is blocked on: https://github.com/emk/rust-musl-builder/pull/126. Please see the discussion there.

And yes, muslrust is a fine choice!

**Comment by emk** [comment]
We now have up-to-date nightly builds using GitHub CI! Thank you to everyone for the encouragement.
