### ISSUE TITLE
Current nightly image currently failing

### ISSUE THREAD

**Issue by beefsack** [emk/rust-musl-builder#16]
First up, fantastic script and Docker image, it has been revolutionary in getting static builds deployed through CI for me 👍 

Looks like the current nightly image is broken though due to [a cargo issue from last month](https://github.com/rust-lang/cargo/issues/3844), would it be at all possible to have a new image built from the Dockerfile? It's currently stopping me from being able to use this to deploy a Rocket app.

The error looks like the following:

```
mick@mick-pc ~/D/b/api (master)> ./build-release 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Thanks!
Michael

**Comment by emk** [comment]
I'm trying a new build. Could you please check in an hour or two from now, and let me know if it works? Thank you!

**Comment by beefsack** [comment]
Works a treat, cheers!
