### ISSUE TITLE
Update image in docker hub

### ISSUE THREAD

**Issue by mersinvald** [emk/rust-musl-builder#18]
Please rebuild the image and upload it to the Docker Hub as stable Rust 1.17 landed recently.

**Comment by emk** [comment]
Thank you for letting me know!

**Comment by emk** [comment]
The build is in progress, and may be ready in an hour or two. If you see that it has been updated at some point, and if you have a spare second, could you please close this issue? Thank you!

**Comment by mersinvald** [comment]
@emk can you check if build was successfull? 

`docker pull ekidd/rust-musl-builder` have nothing to update and it've been more then 4 hours.

**Comment by emk** [comment]
Retrying! Should maybe be something in an hour. Thank you for letting me know!

**Comment by mersinvald** [comment]
@emk image is updated now, thank you!
Closing the issue
