### ISSUE TITLE
Consider including SQLite in the image

### ISSUE THREAD

**Issue by euclio** [emk/rust-musl-builder#28]
Diesel supports sqlite as an option, so it'd be nice to include it.

**Comment by emk** [comment]
Ooh, that's a great idea! I'd happily accept a PR that:

- [ ] Adds SQLite dev packages to the [Ubuntu part of the image](https://github.com/emk/rust-musl-builder/blob/4959d3188a8864597adb9b9bff2827e08c4a4ab5/Dockerfile#L17-L28).
- [ ] Adds a static version of SQLite [installed in `/usr/local/musl`](https://github.com/emk/rust-musl-builder/blob/4959d3188a8864597adb9b9bff2827e08c4a4ab5/Dockerfile#L78-L85).
- [ ] Includes a test case in `examples/using-diesel` to make sure MySQL links correctly. It would need to be added [to the `Cargo.toml` file](https://github.com/emk/rust-musl-builder/blob/4959d3188a8864597adb9b9bff2827e08c4a4ab5/examples/using-diesel/Cargo.toml#L7-L8) and to [`main.rs`](https://github.com/emk/rust-musl-builder/blob/4959d3188a8864597adb9b9bff2827e08c4a4ab5/examples/using-diesel/src/main.rs).

Unfortunately, I won't be able to work on this myself any time soon, but I'd be happy to answer questions if anybody wants to try their hand at it. Mostly it's just a matter of messing around with compiler flags and being slightly frustrated.

But it would be a very welcome addition, and I would try to merge the PR as quickly as I can!
