### ISSUE TITLE
Possible to upgrade nightly to 1.25.0?

### ISSUE THREAD

**Issue by cmac4603** [emk/rust-musl-builder#32]
`docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly cargo build --release`

Trying to build a rust rocket webserver container, but getting this error:
```
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rocket v0.3.6`
process didn't exit successfully: `/home/rust/src/target/release/build/rocket-739bb9e3dbfc16ec/build-script-build` (exit code: 101)
--- stderr
Error: Rocket requires a more recent version of rustc.
Use `rustup update` or your preferred method to update Rust.
Installed version is: 1.24.0-nightly (2018-01-03). Minimum required: 1.25.0-nightly (2018-01-12).
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.3.6/build.rs:50:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Or is there a better way to do this?

**Comment by cmac4603** [comment]
Would you be at all interested in my company copying and recreating the docker image on a weekly basis if I enquired regarding thisi? Or is there already another image doing this?

**Comment by emk** [comment]
I tend to update this image once per stable Rust release, though sometimes I forget for a week or so. The build is parameterized, however, to make it easy for you to rebuild it with specific nightlies if you need to do so.

**Comment by emk** [comment]
I just ran a new build for 1.24.0, which will also build currently nightlies. If you want to rebuild them more regularly, please feel free.
