### ISSUE TITLE
Use of bindgen

### ISSUE THREAD

**Issue by siscia** [emk/rust-musl-builder#49]
Hi,

thanks for this amazing docker file, it was really helpful.

In my project I use bindgen which requires:

`llvm-3.9-dev libclang-3.9-dev clang-3.9`

Can we install them in the docker file?

They increase sensibly the overall size of the image.

I can go ahead and provide a PR if needed.

**Comment by emk** [comment]
That's an excellent idea! I'd really love to have those packages, and a PR would be welcome.

Do you have any idea how many MBs those packages add to the image? I suppose that we should check this first. :-)

**Comment by siscia** [comment]
I am working on it now.

From what I can see:

```
rust@0dcb273013b1:~/src$ sudo apt-get install llvm-3.9-dev libclang-3.9-dev clang-3.9                                                                                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  binfmt-support libclang-common-3.9-dev libclang1-3.9 libffi-dev libllvm3.9 libobjc-5-dev libobjc4 libpipeline1 libpython-stdlib libpython2.7-minimal
  libpython2.7-stdlib libtinfo-dev llvm-3.9 llvm-3.9-runtime mime-support python python-minimal python2.7 python2.7-minimal
Suggested packages:
  gnustep gnustep-devel clang-3.9-doc llvm-3.9-doc python-doc python-tk python2.7-doc
The following NEW packages will be installed:
  binfmt-support clang-3.9 libclang-3.9-dev libclang-common-3.9-dev libclang1-3.9 libffi-dev libllvm3.9 libobjc-5-dev libobjc4 libpipeline1 libpython-stdlib
  libpython2.7-minimal libpython2.7-stdlib libtinfo-dev llvm-3.9 llvm-3.9-dev llvm-3.9-runtime mime-support python python-minimal python2.7 python2.7-minimal
0 upgraded, 22 newly installed, 0 to remove and 0 not upgraded.
Need to get 97.1 MB of archives.
After this operation, 628 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

I am not sure if those 628MB will be reduced once we put everything inside the docker image, but I am quite pessimistic.

**Comment by siscia** [comment]
I believe the options you provided are quite clear and the best way forward.

Thanks for your time. I am closing the issue now.
