### ISSUE TITLE
libraries w/ c dependecies don't compile inside musl builder

### ISSUE THREAD

**Issue by Licenser** [emk/rust-musl-builder#52]
I'm not sure where to exactly open this so I'll link it here too: https://github.com/fede1024/rust-rdkafka/issues/88

**Comment by emk** [comment]
Unfortunately, you'll need to compile the C libraries you need using `musl-gcc`, being careful to set up all the necessary flags. You may also need to tweak the Rust crate in some cases. There's no way to automate this; statically building C libraries will require getting your hands dirty.

See https://github.com/emk/rust-musl-builder#adding-more-c-libraries for some notes and for an example of how to add a new C library.
