### ISSUE TITLE
Use Alpine Linux chroot to get a musl bundle with package management

### ISSUE THREAD

**Issue by sybblow** [emk/rust-musl-builder#6]
It's will be nice to use [Alpine Linux chroot environment](https://wiki.alpinelinux.org/wiki/Installing_Alpine_Linux_in_a_chroot) as the **musl** header and library bundle, so users can use package management tool to add C libraries instead of compile it themselves. They can just chroot into Alpine root and then use **apk**, or even use **apk.static** directly. Is there any technical issue to stop from doing that?

**Comment by emk** [comment]
Well, the big issue is that the Rust install lives _outside_ the chroot, so it's hard to see both the compiler and the Alpine environment at the same time. Unless you only wanted the chroot for the install?

I'd be very interested in looking at a patch which implemented this. I use Alpine a fair bit, but I'm pretty clueless about how it handles static libraries.

**Comment by sybblow** [comment]
I mean just **use Alpine root as bundle of musl C libraries**. `chroot` is only needed when install package for Alpine root, we still use Rust toolchains outside. But we set the gcc to link to Alpine's musl C libraries. It's still a cross-compile, the only different is we can use Alpine's library binaries without need to build them ourselves. And with its package management and package build system, there may be easy library remove and packaging reuse.

I've done some experiment on it, base on the **gcc spec** file you put in this container environment. My host system is Fedora 24 with gcc 6, and **simple hello world C program can be built statically with Alpine musl C (with '-static' option) in this way correctly**.

But the problem is its cooperation with cmake and cargo. First, we need to specify many directory config pointed to Alpine root through system environment variable to make cmake work. And this seems to have lot's of problems, the libssh2-sys seems to be compiled improperly, I think I've already stuck on this. 

I think maybe cargo has some options to solve this, but since cargo is too complicated, I haven't find a answer now.

**Comment by emk** [comment]
I can get cargo to do whatever we need it to do. My concern here is that I
don't know how to get Alpine Linux to use static libraries exclusively. It
might be pretty easy, but I've never looked.

Le 22 juil. 2016 10:24 PM, "Siliang Cao" <notifications@github.com> a
écrit :

**Comment by emk** [comment]
I'm leaving this bug open because I'd love to have some way to install static C libraries using `apk` and link them into Rust executables, but I don't have the time to figure it out myself. If somebody has a demonstration of how to make this work, please let me know.

**Comment by sybblow** [comment]
Alpine Linux has its [own port of rust](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/rust) now. This can make the work much easy, but there still has the same problem mentioned above:  install static C libraries, and link them into Rust executables.

**Comment by jirutka** [comment]
FYI, you can use [alpine-chroot-install](https://github.com/jirutka/alpine-chroot-install) to easily install and use Alpine in chroot on CI, incl. emulation of other arch.

**Comment by emk** [comment]
@sybblow The Alpine Rust port was still 1.10 as of a few weeks ago. It's from before the `?` operator landed. I wonder if they've updated to 1.13 or 1.14 stable yet? Once they start tracking the 6-week update cycle with some reasonable regularity, then I'll be happy to look at that approach.

@jirutka Interesting! But won't that chroot contain shared Alpine libraries and not static ones? One of my goals is a single binary that works on both Alpine and Ubuntu.

**Comment by sybblow** [comment]
I just suggest to use **chroot** Alpine Linux as a "filesystem tree" of **musl libraries**, you can still use offical glibc version rustc compiler and normal gcc in the "host" system as the toolchain, but just with some configuration to make the target to link with Alpine's musl static libraries.

**Comment by emk** [comment]
Thank you for the suggestions!

Since nobody has any working code showing how this would actually work, and I certainly don't have either the time or need to tackle it myself, I'm going to close this issue. If anybody has working code, please feel free to submit a PR.

**Comment by jirutka** [comment]
@emk We have updated Alpine Rust port to the latest version some time ago (currently 1.22.1). Both static and dynamic linking against musl libc is fully working.

**Comment by emk** [comment]
@jirutka Nice!

For me, the big challenge isn't linking statically against `musl-libc`. It's figuring out how to link statically against OpenSSL and `libpq`, primarily. Does Alpine provide static versions of those libraries in an easy-to-link form?
