### ISSUE TITLE
Please update nightly to 1.32.0

### ISSUE THREAD

**Issue by wafflespeanut** [emk/rust-musl-builder#62]
The existing nightly is encountering an ICE (rust-lang/rust#55376) when compiling hyper, which has been fixed upstream.

@emk Could you please update the nightly build?

**Comment by emk** [comment]
I'm re-running the `beta` and `nightly` builds, and they should finish in a few hours, depending on the TravisCI queue. Please let me know if it works!

**Comment by wafflespeanut** [comment]
It works! Thank you :)
