### ISSUE TITLE
rust-musl-builder and DinD CI

### ISSUE THREAD

**Issue by kariae** [emk/rust-musl-builder#68]
Hello, I'm trying to use `rust-musl-builder` in my CI flow I use droneCI for that, that means I'm running a DinD so when I run `rust-musl-builder cargo build --target=aarch64-unknown-linux-gnu --release` I have the following error `could not find Cargo.toml in /home/rust/src` cause for some reason the volume doesn't mount in the last container

**Comment by emk** [comment]
Instead of mounting the source, you may need to `ADD` it using a `Dockefile`. See the `examples/` directory. There should be a few examples of this.

**Comment by kariae** [comment]
Hum, that means to build the Docker image inside the integration process and the execute it, right?

**Comment by emk** [comment]
See the sample `Dockerfile` in [the CI section of the README](https://github.com/emk/rust-musl-builder#making-static-releases-with-travis-ci-and-github). This can probably be adapted to whatever CI system you use.

**Comment by kariae** [comment]
Perfect, thank you 👍
