### ISSUE TITLE
Hashbrown not compiling on nightly

### ISSUE THREAD

**Issue by sd2k** [emk/rust-musl-builder#71]
The `alloc` feature has been stabilised since 2019-04-13 so the nightly image will need to be recreated. Thanks!

**Comment by emk** [comment]
I've kicked off a build that will be tagged `nightly-2019-04-17`, that should contain the bits that you want.

**Comment by emk** [comment]
The `ekidd/rust-musl-builder:nightly-2019-04-17` build is now available. Please re-open this issue if you have any problems!
