### ISSUE TITLE
libunwind symbols not found nightly-2019-12-19

### ISSUE THREAD

**Issue by drahnr** [emk/rust-musl-builder#87]
**How could this project be improved?**

Add libunwind.

Some nightly versions and cargo require it (tested with: 
```
cargo b
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo)
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetIPInfo: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetDataRelBase: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetRegionStart: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_SetGR: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_FindEnclosingFunction: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetTextRelBase: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_Resume: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_RaiseException: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetIP: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_Backtrace: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetLanguageSpecificData: symbol not found
Error relocating /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-musl/bin/cargo: _Unwind_SetIP: symbol not found
```

**Comment by drahnr** [comment]
So it seems I made a mistake and missed the fact that `rustup default nightly-x86_64-unknown-linux-musl` updates the toolchain to the latest.
As such that one was used, including cargo, which now depends on libunwind.

**Comment by drahnr** [comment]
Actually the issue persists, even after assuring only one toolchain (the tagged one is present).

**Comment by emk** [comment]
Thank you for the bug report!

Before we release images, we run the scripts [hooks/build](https://github.com/emk/rust-musl-builder/blob/master/hooks/build) and [hooks/test](https://github.com/emk/rust-musl-builder/blob/master/hooks/test). The test script compiles and links [examples/using-diesel](https://github.com/emk/rust-musl-builder/tree/master/examples/using-diesel).

Please try taking a fresh `rust-musl-builder` image and compiling `using-diesel` as shown in `hooks/test`. Be careful not to upgrade the Rust toolchain. This _should_ work, but if it doesn't, we'll learn more about the problem.

I've also scheduled two builds of `nightly-2020-01-26` (one with OpenSSL 1.0 and one with OpenSSL 1.1). This should allow us to see if `using-diesel` still links correctly with the latest nightly.

Thank you for your help debugging this!

**Comment by drahnr** [comment]
I tested as requested and the root cause here was my own fault, I accidentally mapped `$HOME/.cargo` into the container rather than the `registry`/`git` subdir.
My apologies for the noise.
