### ISSUE TITLE
Question: Testing with rust-musl-builder image

### ISSUE THREAD

**Issue by Mastermindaxe** [emk/rust-musl-builder#93]
Hey everyone,

I'm running into a problem with this image. I can't use `cargo check` or `cargo test` on my system as it can't find OpenSSL on my Windows machine. This might be unrelated, but I figured I'd ask anyways.
How would I go about running tests with the rust-musl-builder? I.e. I don't want to run the tests inside my Dockerfile, but run the tests inside the rust-musl-builder image on my local system. Any help is appreciated.
Apologies if this is not the right place to ask

**Comment by emk** [comment]
Basically, look at the various examples in the docs, and replace `cargo build` with `cargo test`. You could use `docker run my-image cargo test` or something like that.
