### ISSUE TITLE
Add cargo deb support

### ISSUE THREAD

**Issue by bitzl** [emk/rust-musl-builder#94]
**How could this project be improved?**

This Docker image is a great basis for all our Rust CI builds, but to create debian packages, we have to maintain our own Docker image based on this one, only adding the [cargo deb](https://github.com/mmstick/cargo-deb) command. Adding `cargo deb` to this Docker image  would enable building Debian packages right away.

**If you're interested in implementing this feature yourself, how could I help you?**
I can provide a pull request installing the `cargo deb` command.

**Comment by emk** [comment]
Yes, I would definitely be interested in a pull request for this! It's a great idea. Thank you.
